export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import "~/styles/globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-masala-950 h-screen">

        {children}
      </body>
    </html>
  )
}
